#pragma config(Sensor, S1,     light,          sensorEV3_Color)
#pragma config(Sensor, S2,     touchRight,     sensorEV3_Touch)
#pragma config(Sensor, S4,     ultraSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          Left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          Right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//void turn180(long nMotorRatio, long power);

//void drive(long nMotorRatio, long dist, long power);

#define Centimetre 20.93

task main()
{
	int value1=0;
	int value2=0;
	int average=0;


	//displayCenteredBigTextLine(4,"Distance %d",dist);

	while ((getButtonPress(buttonDown))== 0)
	{
		displayCenteredBigTextLine(4,"Light = %d",SensorValue(light));
	  displayCenteredBigTextLine(8,"Light = %d",value2);
	  displayCenteredBigTextLine(12,"Threshold = %d",average);

	  sleep(20);
		if (getButtonPress(buttonDown))
		{
			value1= SensorValue(light);
		}

	}
	sleep(500);

	while ((getButtonPress(buttonDown))== 0)
	{
		displayCenteredBigTextLine(4,"Light = %d",value1);
	  displayCenteredBigTextLine(8,"Light = %d",SensorValue(light));
	  displayCenteredBigTextLine(12,"Threshold = %d",average);

	  sleep(20);
		if (getButtonPress(buttonDown))
		{
			value2= SensorValue(light);
		}

	}

	average= (value1+value2)/2;
	displayCenteredBigTextLine(4,"Light = %d",value1);
  displayCenteredBigTextLine(8,"Light = %d",SensorValue(light));
  displayCenteredBigTextLine(12,"Threshold = %d",average);

  sleep(10000);
}

/*
void turn180(long nMotorRatio, long power)
{

	resetMotorEncoder(Left);
	resetMotorEncoder(Right);

	setMotorSyncEncoder(Left, Right, nMotorRatio, 360, power);

	waitUntilMotorStop(Right);

}

void drive(long nMotorRatio, long dist, long power)
{
	int rotations = (Centimetre * dist);

	resetMotorEncoder(Left);
	resetMotorEncoder(Right);

	setMotorSyncEncoder(Left, Right, nMotorRatio, rotations, power);

	waitUntilMotorStop(Right);
}
*/
