#pragma config(Sensor, S1,     Light,          sensorEV3_Color)
#pragma config(Sensor, S2,     touchRight,     sensorEV3_Touch)
#pragma config(Sensor, S4,     Ultra,          sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          Left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          Right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void turn90(long nMotorRatio, long power);

void drive(long nMotorRatio, long dist, long power);

#define Centimetre 20.93

task main()
{
	while (!SensorValue(touchRight))
	{
		setMotorSpeed(Left, 20);
		setMotorSpeed(Right, 35);

		if (SensorValue(Ultra) < 15)
		{
			turn90(-100, 40);
			drive(0, 15, 40);
			turn90(100, 40);
			drive(0, 40, 40);
			turn90(100, 40);
			drive(0, 15, 40);
			turn90(-100, 40);
		}
		if (SensorValue(Light) < 40)
		{
			setMotorSpeed(Left, 50);
			setMotorSpeed(Right, 20);

		}

	}

}


void turn90(long nMotorRatio, long power)
{

	resetMotorEncoder(Left);
	resetMotorEncoder(Right);

	setMotorSyncEncoder(motorB, motorC, nMotorRatio, 180, power);

	waitUntilMotorStop(Right);

}


void drive(long nMotorRatio, long dist, long power)
{
	int rotations = (Centimetre * dist);

	resetMotorEncoder(Left);
	resetMotorEncoder(Right);

	setMotorSyncEncoder(Left, Right, nMotorRatio, rotations, power);

	waitUntilMotorStop(Right);
}
