#pragma config(Sensor, S1,     Light,          sensorEV3_Color)
#pragma config(Sensor, S2,     touchRight,     sensorEV3_Touch)
#pragma config(Sensor, S4,     Ultra,          sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          Left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          Right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#define Centimetre 20.93

task main()
{
	while (!SensorValue(touchRight))
	{
		setMotorSpeed(Left, 20);
		setMotorSpeed(Right, 35);

		if (SensorValue(Light) < 40)
		{
			setMotorSpeed(Left, 50);
			setMotorSpeed(Right, 20);

		}

	}

}
