#pragma config(Sensor, S1,     Light,          sensorEV3_Color)
#pragma config(Sensor, S2,     touchRight,     sensorEV3_Touch)
#pragma config(Sensor, S4,     ultraSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          Left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          Right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//void turn90(long nMotorRatio, long power);

void drive(long nMotorRatio, long dist, long power);

#define Centimetre 20.93

task main()
{
	int count = 0;


	while (!SensorValue(touchRight))
	{
		setMotorSpeed(Left, 50);
		setMotorSpeed(Right, 50);

		if (SensorValue(Light) < 40)
		{
			count++;
			displayCenteredBigTextLine(3, "Black Lines: %d", count);
			setMotorSpeed(Left, 0);
			setMotorSpeed(Right, 0);
			sleep(500);
			drive(0 ,3 ,50);


		}

	}

}

/*
void turn90(long nMotorRatio, long power)
{

	resetMotorEncoder(Left);
	resetMotorEncoder(Right);

	setMotorSyncEncoder(motorB, motorC, nMotorRatio, 170, power);

	waitUntilMotorStop(Right);

}
*/

void drive(long nMotorRatio, long dist, long power)
{
	int rotations = (Centimetre * dist);

	resetMotorEncoder(Left);
	resetMotorEncoder(Right);

	setMotorSyncEncoder(Left, Right, nMotorRatio, rotations, power);

	waitUntilMotorStop(Right);
}
