#pragma config(Sensor, S1,     light,          sensorEV3_Color)
#pragma config(Sensor, S2,     touchRight,     sensorEV3_Touch)
#pragma config(Sensor, S4,     ultraSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          Left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          Right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//void turn180(long nMotorRatio, long power);

//void drive(long nMotorRatio, long dist, long power);

#define Centimetre 20.93

task main()
{
	int count= 0;
	//displayCenteredBigTextLine(4,"Distance %d",dist);

	while ((getButtonPress(buttonDown))== 0)
	{
		displayCenteredBigTextLine(4,"Light = %d",SensorValue(light));

		if ((SensorValue(light)>40) && (count%2==0))
		{
			setMotorSpeed(Left,20);
			setMotorSpeed(Right,-20);
			sleep(count);
			count= count + 51;
		}

		else if ((SensorValue(light)>40) && (count%2==1))
		{
			setMotorSpeed(Left,-20);
			setMotorSpeed(Right,20);
			sleep(count);
			count= count + 51;

		}

		else if (SensorValue(light)<40)
		{
			count = 0;
			setMotorSpeed(Left,20);
			setMotorSpeed(Right,20);
			sleep(20);
		}
	}

}

/*
void turn180(long nMotorRatio, long power)
{

	resetMotorEncoder(Left);
	resetMotorEncoder(Right);

	setMotorSyncEncoder(Left, Right, nMotorRatio, 360, power);

	waitUntilMotorStop(Right);

}

void drive(long nMotorRatio, long dist, long power)
{
	int rotations = (Centimetre * dist);

	resetMotorEncoder(Left);
	resetMotorEncoder(Right);

	setMotorSyncEncoder(Left, Right, nMotorRatio, rotations, power);

	waitUntilMotorStop(Right);
}
*/
