#pragma config(Sensor, S1,     touchLeft,      sensorEV3_Touch)
#pragma config(Sensor, S2,     touchRight,     sensorEV3_Touch)
#pragma config(Sensor, S4,     ultraSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          Left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          Right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void turn180(long nMotorRatio, long power);

void drive(long nMotorRatio, long dist, long power);

#define Centimetre 20.93

task main()
{
	int ranNum = random(100);
	int dist= 10;
	int incRight= 0;

	while (getButtonPress(buttonEnter) == 0 )
	{
		sleep(200);

		if (getButtonPress(buttonUp))
		{
			incRight++;
		}

		if (getButtonPress(buttonDown))
		{
			incRight--;
		}

		if (incRight % 4==1)
		{
			dist = 40;
			displayCenteredBigTextLine(4,"Distance %d",dist);
		}

		if (incRight % 4==2)
		{
			dist = 60;
			displayCenteredBigTextLine(4,"Distance %d",dist);
		}

		if (incRight % 4==3)
		{
			dist = 80;
			displayCenteredBigTextLine(4,"Distance %d",dist);

		}

		if (incRight % 4==0)
		{
			dist = 10;
			displayCenteredBigTextLine(4,"Distance %d",dist);

		}
	}
	drive(0, dist, ranNum);
}

void turn180(long nMotorRatio, long power)
{

	resetMotorEncoder(Left);
	resetMotorEncoder(Right);

	setMotorSyncEncoder(Left, Right, nMotorRatio, 360, power);

	waitUntilMotorStop(Right);

}

void drive(long nMotorRatio, long dist, long power)
{
	int rotations = (Centimetre * dist);

	resetMotorEncoder(Left);
	resetMotorEncoder(Right);

	setMotorSyncEncoder(Left, Right, nMotorRatio, rotations, power);

	waitUntilMotorStop(Right);
}
