#pragma config(Motor,  motorB,          Left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          Right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void turn180(long nMotorRatio, long power);
#pragma config(Motor,  motorB,          Left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          Right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void turn180(long nMotorRatio, long power);

void drive(long nMotorRatio, long dist, long power);

#define Centimetre 20.93

task main()
{
	int ranNum = random(1);

	drive(0, 100, 100);

	if(ranNum == 1)
	{
		turn180(100, 50);
	}
	else
	{
		turn180(-100, 50);
	}

	drive(0, 100, 25);

}

void turn180(long nMotorRatio, long power)
{

	resetMotorEncoder(Left);
	resetMotorEncoder(Right);

	setMotorSyncEncoder(Left, Right, nMotorRatio, 360, power);

	waitUntilMotorStop(Right)

}

void drive(long nMotorRatio, long dist, long power)
{
	int rotations = (Centimetre * dist);

	resetMotorEncoder(Left);
	resetMotorEncoder(Right);

	setMotorSyncEncoder(Left, Right, nMotorRatio, rotations, power);

	waitUntilMotorStop(Right)
}
