#pragma config(Motor,  motorB,          Left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          Right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void turn90(long nMotorRatio, long power);

void drive(long nMotorRatio, long dist, long power);

#define Centimetre 20.93

task main()
{
	int ranNum = random(1);
	int direction;


	if(ranNum == 1)
	{
		direction = 100;
	}
	else
	{
		direction = -100;
	}

	drive(0, 60, 50);
	turn90(direction, 50);
	drive(0, 60, 50);
	turn90(direction, 50);
	drive(0, 60, 50);
	turn90(direction, 50);
	drive(0, 60, 50);

}

void turn90(long nMotorRatio, long power)
{

	resetMotorEncoder(Left);
	resetMotorEncoder(Right);

	setMotorSyncEncoder(Left, Right, nMotorRatio, 170, power);

	waitUntilMotorStop(Right)

}

void drive(long nMotorRatio, long dist, long power)
{
	int rotations = (Centimetre * dist);

	resetMotorEncoder(Left);
	resetMotorEncoder(Right);

	setMotorSyncEncoder(Left, Right, nMotorRatio, rotations, power);

	waitUntilMotorStop(Right)
}
