#pragma config(Motor,  motorB,          Left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          Right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//




void turn90(long nMotorRatio, long power)
{

	setMotorSyncEncoder(Left, Right, nMotorRatio, power);

}

void drive(long nMotorRatio, long dist, long power)
{
	setMotorSyncEncoder(Left, Right, nMotorRatio, dist, power);
}



task main()
{
	drive(0, 2000, 100);


}
